# Site settings
title: Lisha
description: 'Current PhD Student at UC Berkeley Statistics'
url: 'http://lishali.github.io' 
baseurl: ''
google_analytics: 'UA-73314404-1'

author:
  name: 'Lisha Li'
  email: lisha@berkeley.edu
  twitter_username: lisha29143106
  github_username: lishali
  linkedin_username: lisha-li-700985a

# Build settings
destination: _site
paginate: 10
permalink: /:year/:title/
markdown: redcarpet
highlighter: pygments

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false

gems: ['jekyll-paginate', 'jekyll-mentions', 'jemoji', 'jekyll-redirect-from', 'jekyll-sitemap', 'jekyll-feed']
exclude: ['README.md', 'Gemfile', 'Gemfile.lock', 'screenshot.png']
